export const awards = [
  {
    name: "Card Gallery Scroll",
    type: "3D",
    project: "Check it out",
    label: "3⋇D",
    url: "https://3d-card-gallery-scroll.vercel.app/",
  },
  {
    name: "Animated Card Section",
    type: "Card",
    project: "Check it out",
    label: "C⋇rD",
    url: "https://animated-card-section.vercel.app/",
  },
  {
    name: "Phive Text Scroll",
    type: "Scroll",
    project: "Check it out",
    label: "Scr⋇ll",
    url: "https://phive-text-scroll-anim.vercel.app/",
  },
  {
    name: "Telescope img scroll",
    type: "Scroll",
    project: "Check it out",
    label: "Scr⋇ll",
    url: "https://telescope-img-scroll.vercel.app/",
  },
  {
    name: "Whole page navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://whole-page-navbar.vercel.app/",
  },
  {
    name: "Path scroll",
    type: "Scroll",
    project: "Check it out",
    label: "Scr⋇ll",
    url: "https://path-scroll-anim.vercel.app/",
  },
  {
    name: "Block Page Transition",
    type: "transition",
    project: "Check it out",
    label: "transiti⋇n",
    url: "https://page-transition-livid.vercel.app/",
  },
  {
    name: "nvg8-scroll",
    type: "Scroll",
    project: "Check it out",
    label: "Scr⋇ll",
    url: "https://nvg8-inspired-scroll-anim.vercel.app/",
  },
  {
    name: "Futuristic navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://futuristic-navbar.vercel.app/",
  },
  {
    name: "img shuffle preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://img-shuffle-landing-page.vercel.app/",
  },
  {
    name: "draggable img",
    type: "draggable",
    project: "Check it out",
    label: "dragg⋇ble",
    url: "https://phantom-inspired-draggable-img.vercel.app/",
  },
  {
    name: "p10 preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://p10-inspired-landing-page.vercel.app/",
  },
  {
    name: "inkwell gallery",
    type: "gallery",
    project: "Check it out",
    label: "gall⋇ry",
    url: "https://inkwell-inspired-gallery.vercel.app/",
  },
  {
    name: "gta VI landing",
    type: "landing",
    project: "Check it out",
    label: "l⋇nding",
    url: "https://gta-6-landing-page-henna.vercel.app/",
  },
  {
    name: "Scroll carousel",
    type: "carousel",
    project: "Check it out",
    label: "car⋇usel",
    url: "https://scroll-carousel.vercel.app/",
  },
  {
    name: "Scroll img transition",
    type: "transition",
    project: "Check it out",
    label: "transiti⋇n",
    url: "https://scroll-transition-img.vercel.app/",
  },
  {
    name: "preload reveal",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://landing-page-reveal-wine.vercel.app/",
  },
  {
    name: "Scroll anim",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://scroll-anim-ten.vercel.app/",
  },
  {
    name: "Responsive img minimap",
    type: "gallery",
    project: "Check it out",
    label: "gall⋇ry",
    url: "https://responsive-img-minimap.vercel.app/",
  },
  {
    name: "Sticky Card",
    type: "card",
    project: "Check it out",
    label: "c⋇rd",
    url: "https://sticky-card.vercel.app/",
  },
  {
    name: "Star Path preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://star-reveal-anim.vercel.app/",
  },
  {
    name: "cube morphing",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-cube-morphing.vercel.app/",
  },
  {
    name: "Horizontal Scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://horizontal-scroll-ten.vercel.app/",
  },
  {
    name: "infinite scroll parallax",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://infinite-scroll-parallax-fawn.vercel.app/",
  },
  {
    name: "Triangle Transition",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://scroll-triangle-transition.vercel.app/",
  },
  {
    name: "infinite carousel",
    type: "carousel",
    project: "Check it out",
    label: "car⋇usel",
    url: "https://infinite-carousel-ten.vercel.app/",
  },
  {
    name: "modern img reveal",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://modern-img-landing-page.vercel.app/",
  },
  {
    name: "water hover effect",
    type: "shader",
    project: "Check it out",
    label: "shad⋇r",
    url: "https://water-hover-effect.vercel.app/",
  },
  {
    name: "awwwards scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://awwwards-scroll-anim.vercel.app/",
  },
  {
    name: "curve img scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://curve-img-scroll.vercel.app/",
  },
  {
    name: "card horizontall scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://card-horizontal-scroll.vercel.app/",
  },
  {
    name: "circular img",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-circular-img.vercel.app/",
  },
  {
    name: "3d chair scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://3d-scroll-chair.vercel.app/",
  },
  {
    name: "happy preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://happy-landing-page.vercel.app/",
  },
  {
    name: "3d drag around",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-scroll-around.vercel.app/",
  },
  {
    name: "3d room",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-room-six.vercel.app/cg-brutalist-corridor-lp/index.html",
  },
  {
    name: "3d scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://3d-scroll-seven.vercel.app/",
  },
  {
    name: "pin gallery",
    type: "gallery",
    project: "Check it out",
    label: "gall⋇ry",
    url: "https://pin-gallery-psi.vercel.app/",
  },
  {
    name: "digital carousel",
    type: "carousel",
    project: "Check it out",
    label: "car⋇usel",
    url: "https://digital-carousel.vercel.app/",
  },
  {
    name: "anim slider",
    type: "slider",
    project: "Check it out",
    label: "slid⋇r",
    url: "https://anim-slider.vercel.app/",
  },
  {
    name: "flipping card",
    type: "card",
    project: "Check it out",
    label: "c⋇rd",
    url: "https://flipping-card-beta.vercel.app/",
  },
  {
    name: "Scroll anim per img",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://scroll-anim-per-img.vercel.app/",
  },
  {
    name: "3d tunnel",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-tunnel-img.vercel.app/",
  },
  {
    name: "img selection",
    type: "transition",
    project: "Check it out",
    label: "transiti⋇n",
    url: "https://img-selection-scroll.vercel.app/",
  },
  {
    name: "3d cards",
    type: "3d",
    project: "Check it out",
    label: "3⋇d",
    url: "https://3d-card-lake.vercel.app/",
  },
  {
    name: "awwwards navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://ratio-navbar.vercel.app/",
  },
  {
    name: "marquee hover img",
    type: "hover",
    project: "Check it out",
    label: "h⋇ver",
    url: "https://marquee-hover-direction.vercel.app/",
  },
  {
    name: "vucko preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://vucko-landing-page.vercel.app/",
  },
  {
    name: "text hover shader",
    type: "shader",
    project: "Check it out",
    label: "shad⋇r",
    url: "https://text-hover-shader.vercel.app/",
  },
  {
    name: "3d video slider",
    type: "slider",
    project: "Check it out",
    label: "slid⋇r",
    url: "https://3d-video-slider-chi.vercel.app/",
  },
  {
    name: "shader distortion",
    type: "shader",
    project: "Check it out",
    label: "shad⋇r",
    url: "https://shader-distortion.vercel.app/",
  },
  {
    name: "interactive calendar",
    type: "card",
    project: "Check it out",
    label: "c⋇rd",
    url: "https://interactive-calendar-cards.vercel.app/",
  },
  {
    name: "physics landing anim",
    type: "transition",
    project: "Check it out",
    label: "transiti⋇n",
    url: "https://physics-landing-page-two.vercel.app/",
  },
  {
    name: "img gallery layout",
    type: "gallery",
    project: "Check it out",
    label: "gall⋇ry",
    url: "https://img-gallery-layout.vercel.app/",
  },
  {
    name: "instagram stories",
    type: "slider",
    project: "Check it out",
    label: "slid⋇r",
    url: "https://instagram-stories-seven.vercel.app/",
  },
  {
    name: "mask img reveal",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://mask-reveal.vercel.app/",
  },
  {
    name: "click carousel",
    type: "carousel",
    project: "Check it out",
    label: "car⋇usel",
    url: "https://click-carousel.vercel.app/",
  },
  {
    name: "img horizontal slider",
    type: "slider",
    project: "Check it out",
    label: "slid⋇r",
    url: "https://img-slider-scroll.vercel.app/",
  },
  {
    name: "variation fonts scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://scrolltrigger-font.vercel.app/",
  },
  {
    name: "text shuffle navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://text-shuffle-navbar.vercel.app/",
  },
  {
    name: "slider click",
    type: "slider",
    project: "Check it out",
    label: "slid⋇r",
    url: "https://slider-click.vercel.app/",
  },
  {
    name: "gothic mouse trail",
    type: "mouse",
    project: "Check it out",
    label: "m⋇use",
    url: "https://gothic-mousetrail.vercel.app/",
  },
  {
    name: "modern preloader",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://modern-preloader-rho.vercel.app/",
  },
  {
    name: "modular carousel",
    type: "carousel",
    project: "Check it out",
    label: "car⋇usel",
    url: "https://modular-carousel.vercel.app/",
  },
  {
    name: "rotating text img hover",
    type: "hover",
    project: "Check it out",
    label: "h⋇ver",
    url: "https://rotating-text-img-hover.vercel.app/",
  },
  {
    name: "draggable scrollbar",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://draggable-scrollbar.vercel.app/",
  },
  {
    name: "blur img navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://blur-img-navbar.vercel.app/",
  },
  {
    name: "img adjust scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://img-adjust-scroll.vercel.app/",
  },
  {
    name: "blocky scroll fade",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://blocky-scroll-fade.vercel.app/",
  },
  {
    name: "mouse move",
    type: "mouse",
    project: "Check it out",
    label: "m⋇use",
    url: "https://mousemove-svg.vercel.app/",
  },
  {
    name: "reveal preload",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://reveal-landing-pages.vercel.app/",
  },
  {
    name: "circle img gallery",
    type: "gallery",
    project: "Check it out",
    label: "gall⋇ry",
    url: "https://circle-img-gallery.vercel.app/",
  },
  {
    name: "horizontal img scroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://horizontal-img-scroll.vercel.app/",
  },
  {
    name: "modern navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://modern-navbar-xi.vercel.app/",
  },
  {
    name: "text shuffle",
    type: "hover",
    project: "Check it out",
    label: "h⋇ver",
    url: "https://text-shuffle.vercel.app/",
  },
  {
    name: "sticky sidebar",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://sticky-sidebar.vercel.app/",
  },
  {
    name: "marquee onscroll",
    type: "scroll",
    project: "Check it out",
    label: "scr⋇ll",
    url: "https://marquee-onscroll.vercel.app/",
  },
  {
    name: "preload curtain",
    type: "preload",
    project: "Check it out",
    label: "prel⋇ad",
    url: "https://reveal-landing-page.vercel.app/",
  },
  {
    name: "slide to choose navbar",
    type: "navbar",
    project: "Check it out",
    label: "navb⋇r",
    url: "https://slide-to-choose-navbar.vercel.app/",
  },
];
